### PR TITLE
Allow passing SSL options via server URL

### PR DESCRIPTION
**Pull request by llucax**

### CODE REVIEW

**Comment by llucax** [comment]
Need some tests, but other than that it is ready for review.

**Comment by Marenz** [comment]
Looks like it should work. I'll try to use it and will report

**Comment by Marenz** [comment]
Works well in my test!

**Comment by llucax** [comment]
OK, this PR was reworked a lot, and now we allow client implementors to set defaults for creating gRPC channels much more flexibly. For example, a default root certificates option can be passed both as a file path or `bytes`. The users also have the option to override these options via the URL.

Marking as ready to review.

**Comment by llucax** [comment]
@Marenz can you re-test and give this a (final?) review?

**Comment by llucax** [comment]
Tests are failing because some breaking change in griffe when generating docs, will look at it ASAP but the review can be done anyways

**Comment by llucax** [comment]
Fixed the CI failure.

**Review by Marenz — APPROVED** [review]

**Pull request merged**
