### PR TITLE
Add method to restart stream when retry strategy is exhausted

### PR DESCRIPTION
**Pull request by Marenz**

### CODE REVIEW

**Comment by llucax** [comment]
Do we really need this? Why not just setting the retry `limit` to `None` (which is the default BTW)?

* https://frequenz-floss.github.io/frequenz-client-base-python/latest/reference/frequenz/client/base/streaming/#frequenz.client.base.streaming.GrpcStreamBroadcaster.__init__
* https://frequenz-floss.github.io/frequenz-client-base-python/latest/reference/frequenz/client/base/retry/#frequenz.client.base.retry.LinearBackoff.__init__

**Comment by Marenz** [comment]
> Do we really need this? Why not just setting the retry limit to None (which is the default BTW)?

I am setting it to None. But how I am _ever_ gonna restart that stream now?

**Comment by Marenz** [comment]
> [..] retry limit to None (which is the default BTW)?

No it's not?!

image

**Comment by llucax** [comment]
> I am setting it to None. But how I am _ever_ gonna restart that stream now?

Why do you want to restart it if it restarts automatically continuously. Maybe you can describe the use case you have in mind more in detail?

> No it's not?!

Yes, **indefinitely**.

https://github.com/frequenz-floss/frequenz-client-base-python/blob/dfdfaf36ece562994af58ca7cfa4be0350fc4038/src/frequenz/client/base/streaming.py#L50-L52

https://github.com/frequenz-floss/frequenz-client-base-python/blob/dfdfaf36ece562994af58ca7cfa4be0350fc4038/src/frequenz/client/base/retry.py#L77-L84

**Comment by Marenz** [comment]
Well, I want an exception to be thrown when the connection fails.

Then I handle it etc.. and then I want to try it again. But i can't, when the retry strategy is exhausted, the whole streamer instance is from that point on useless.

**Comment by llucax** [comment]
> Then the documentation is wrong :P

No, why? It says it retries indefinitely.

> Well, I want an exception to be thrown when the connection fails.

So you don't want to retry indefinitely, you want to have more control, is that the use case?

**Comment by Marenz** [comment]
Yes, that's the usecase. Remember, we wanted to put the handling a level higher?

**Comment by llucax** [comment]
OK, I guess I was confused by the PR title, because in this case you don't want a retry strategy at all, right?

**Comment by Marenz** [comment]
Yes. but I can have that already when I just say "limit=0".
The title just refers to the condition for when it's needed: When the retry condition is exhausted and the channel is closed.

**Comment by llucax** [comment]
OK, looking at it again with the new information, what would be the advantage of being able to restart it compared to create a new streamer? You are rebuilding the whole internal state (recreating the channel, tasks, etc.), so from the efficiency point of view I guess it doesn't make a lot of difference.

For your use case it would be more inconvenient to re-create the streamer instead? In any this PR is fixing a sort of bug, it is not great that if you call `start()` after it was stopped it will misbehave.

But I was wondering if we could still keep the channel opened (or even the task alive). As for the channel, right now it is closed to stop the receivers, I think, so I wonder if this is something we want to do or not.

**Comment by llucax** [comment]
Oh, I guess in your use case you'll just create a new receiver for the streamer when the current receiver stops? If so I can see how it is simpler to use than recreating the whole streamer.

**Review by llucax — APPROVED** [review]
I would update the PR description and commit message to something like "Allow (re)starting a stopped streamer" to make it less confusing, other than that I'm fine with merging this as is and leave other ideas for future improvements.

**Comment by Marenz** [comment]
I mean, i can also recreate the whole instance, sure  https://github.com/frequenz-floss/frequenz-client-dispatch-python/pull/94

**Comment by llucax** [comment]
I'm also fine with both, I wanted to understand the use case better. Both PRs are approved, I leave it to you to chose what to use.

**Review by llucax — APPROVED** [review]

**Pull request closed without merging**
